export const ADD_PERSONAL_DATA = 'ADD_PERSONAL_DATA';
export const ADD_EXPERIENCE_DATA = 'ADD_EXPERIENCE_DATA';
export const ADD_EDUCATION_DATA = 'ADD_EDUCATION_DATA';
export const ADD_EXTRAS_DATA = 'ADD_EXTRAS_DATA';
export const ADD_PHOTO_DATA = 'ADD_PHOTO_DATA';

export const ADD_SAMPLE_EXPERIENCE_DATA = 'ADD_SAMPLE_EXPERIENCE_DATA';
export const EDIT_SINGLE_EXPERIENCE_DATA = 'EDIT_SINGAL_EXPERIENCE_DATA';
export const DELETE_SINGLE_EXPERIENCE_DATA = 'DELETE_SINGAL_EXPERIENCE_DATA';

export const ADD_SAMPLE_EDUCATION_DATA = 'ADD_SAMPLE_EDUCATION_DATA';
export const EDIT_SINGLE_EDUCATION_DATA = 'EDIT_SINGAL_EDUCATION_DATA';
export const DELETE_SINGLE_EDUCATION_DATA = 'DELETE_SINGAL_EDUCATION_DATA';

export const ADD_SAMPLE_EXTRA_DATA = 'ADD_SAMPLE_EXTRA_DATA';
export const EDIT_SINGLE_EXTRA_DATA = 'EDIT_SINGAL_EXTRA_DATA';
export const DELETE_SINGLE_EXTRA_DATA = 'DELETE_SINGAL_EXTRA_DATA';
